### ISSUE TITLE
Run analysis and print figures Error 

### ISSUE THREAD

**Issue by studyyan** [DrCytometer/Simplified-flowcytoscript#2]
Thanks for your simplified flowcytoscript. But I encounter an error when running the step of flowcytoscript_run_analysis.r. 

Error in heatmap(t(flow.data.group.median), scale = "row", labRow = fcs.channel.label, : 'x' must have at least 2 rows and 2 columns
[Uploading flowcytoscript.pdf…]()

In other words, the above error occurred on my Windows computer, and I also have some problems installing FastPG R packages on my Macbook Pro because the omp.h file is missing on the Mac. The detailed error is shown below. 

Is there a solution? Or if the FastPG package is not an essential part of this script, could I delete it from the script? 

In file included from buildNextPhase.cpp:42:
./defs.h:52:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
1 error generated.
make: *** [buildNextPhase.o] Error 1
ERROR: compilation failed for package ‘FastPG’
* removing ‘/Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/library/FastPG’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/dn/jkbwgchs0sn9wn_pg3l3brd00000gn/T//RtmpK4VQH0/file50fc3eba202a/FastPG_0.0.8.tar.gz’ had non-zero exit status

**Comment by DrCytometer** [comment]
So, unfortunately, installing FastPG on a Mac is pretty complicated due to the requirement for OpenMP. I don't have much access to Macs, so I can't provide support for that. I believe I included some instructions if you want to try.

I'll look into generating a Mac-friendly version without FastPG.

The error you've gotten means you're trying to generate a heatmap on data with fewer two rows and columns. Either you've only run one group, only selected one marker, or you've had another error related to the failed install.

**Comment by studyyan** [comment]
Thanks for your answer. I encountered another problem about renaming clusters. After the automatic definition, I did not find any option to rename these clusters when I ran the rmd.

**Comment by DrCytometer** [comment]
Given that it hasn't installed properly for you, you're going to get errors.

Could you try out the attached version? This does not require FastPG, and should work without OpenMP. In my tests on an old iMac without OpenMP, it works.
[20240623_distribution.zip](https://github.com/user-attachments/files/15945510/20240623_distribution.zip)

Sample data for testing this can be downloaded from [Dropbox](https://www.dropbox.com/scl/fo/s9h6z1k3rvliczv08uk6c/AGFFDoxnF1ttcZ7lTvddAQQ?rlkey=d3b224522jgq9g3rds8bnb3s9&dl=0), if you wish.

**Comment by studyyan** [comment]
I'm so grateful to you for helping me with this! The new version has answered all of my questions. Thank you again for your help!

**Comment by DrCytometer** [comment]
Awesome! I'll pass it out to a couple more people for testing, and if it works, update the main code.
